=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/external-synonym/example-7/example-7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="a">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cRef" type="CReference" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="c" type="C" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="Reference">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The abstract base class for all types which define intra-document pointers.
            </xs:documentation>
        </xs:annotation>
    </xs:complexType>

    <xs:complexType name="CReference">
        <xs:annotation>
            <xs:documentation xml:lang="en">Reference to C</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="Reference">
                <xs:attribute name="href" type="xs:IDREF" use="required" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="C">
        <xs:sequence>
            <xs:element name="d" />
            <xs:element name="e" />
            <xs:element name="f" type="FEnum" />
            <xs:element name="g" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:simpleType name="FEnum">
        <xs:restriction base="xs:token">
            <xs:enumeration value="AA">
            </xs:enumeration>
            <xs:enumeration value="BB">
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/conditional-set/example-7/example-7-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-7.xsd example-7.xsd">
    <a>
        <b>
            <d>
                <e>FISH</e>
                <f>CHIPS</f>
            </d>
        </b>
        <c>
            <d>
                <e>FISH2</e>
                <f>CHIPS2</f>
            </d>
        </c>
    </a>
</dataDocument>
