=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/mappers/example-12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="a">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="c"/>
                                        <xs:element type="xs:string" name="d"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="e" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="f"/>
                                        <xs:element type="xs:string" name="g"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/rosetta-source/src/main/resources/cdm-sample-files/conditional-set/example-12/example-12-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-12.xsd example-12.xsd">
    <a>
        <b>
            <c>FISH</c>
            <d>CHIPS</d>
        </b>
        <b>
            <c>SAUSAGE</c>
            <d>GRAVY</d>
        </b>
        <b>
            <c>STEAK</c>
            <d>POTATOS</d>
        </b>
    </a>
</dataDocument>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/mappers/example-12/example-12-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-12.xsd example-12.xsd">
    <a>
        <b>
            <c>FISH</c>
            <d>CHIPS</d>
        </b>
        <b>
            <c>BREAD</c>
            <d>CARROT</d>
        </b>
        <e>
            <f>MEAT</f>
            <g>FISH</g>
        </e>
        <e>
            <f>EGGS</f>
            <g>HAM</g>
        </e>
    </a>
</dataDocument>
