=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/mappers/example-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="top">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="leg" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="a" type="xs:string" />
                                        <xs:element name="b" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/rosetta-source/src/main/resources/cdm-sample-files/mappers/example-2/example-2-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-2.xsd example-2.xsd">
    <top>
        <leg>
            <a>Fish</a>
            <b>Chips</b>
        </leg>
        <leg>
            <a>Sausage</a>
            <b>Mash</b>
        </leg>
    </top>
</dataDocument>
