=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/mappers/example-12/example-12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fuelDetail" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="emissions"/>
                                        <xs:element type="xs:string" name="combustible"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="capacityDetail" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="capacityUnit"/>
                                        <xs:element type="xs:string" name="volumeConsumption"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-12/example-12-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="../example-12/example-12.xsd example-12.xsd">
    <engineType>
        <fuelDetail>
            <combustible>Petrol</combustible>
        </fuelDetail>
        <fuelDetail>
            <combustible>Diesel</combustible>
        </fuelDetail>
        <capacityDetail>
            <capacity>Gallon</capacity>
        </capacityDetail>
        <capacityDetail>
            <capacity>Gallon</capacity>
        </capacityDetail>
    </engineType>
</dataDocument>
