=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-27/example-27.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fuelDetail" type="Detail" maxOccurs="unbounded"/>
                            <xs:element name="capacityDetail" type="Detail" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Detail">
        <xs:sequence>
            <xs:element name="detail" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-27/example-27-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-27.xsd example-27.xsd">
    <engineType>
        <fuelDetail>
            <detail>Petrol</detail>
            <detail>Diesel</detail>
        </fuelDetail>
        <capacityDetail>
            <detail>Litres</detail>
            <detail>Gallon</detail>
        </capacityDetail>
    </engineType>
</dataDocument>
