=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/conditional-set/example-25/example-25.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="combustible" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="combustibleId"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fuelSpecs" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="combustibleref">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="href" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="capacityUnitId"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/conditional-set/example-25/example-25-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-25.xsd example-25.xsd">
    <engineType>
        <combustible id="US">
            <combustibleId>Gasoline</combustibleId>
        </combustible>
        <combustible id="UK">
            <combustibleId>Petrol</combustibleId>
        </combustible>
        <fuelSpecs>
            <combustibleref href="UK"/>
            <capacityUnitId>UK Gallon</capacityUnitId>
        </fuelSpecs>
        <fuelSpecs>
            <combustibleref href="US"/>
            <capacityUnitId>US Gallon</capacityUnitId>
        </fuelSpecs>
    </engineType>
</dataDocument>
