=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-29/example-29.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="a" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b" type="B"/>
                            <xs:element name="f" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="B" mixed="true">
        <xs:sequence>
            <xs:element name="c" type="xs:string"/>
            <xs:element name="d" type="xs:string"/>
            <xs:element name="e" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-29/example-29-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-29.xsd example-29.xsd">
    <a>
        <b>
            <c>c1-value</c>
            <d>d1-value</d>
            <e>e1-value</e>
        </b>
        <f>f1-value</f>
    </a>
    <a>
        <b>
            <c>c2-value</c>
            <d>d2-value</d>
            <e>e2-value</e>
        </b>
        <f>f2-value</f>
    </a>
</dataDocument>
