=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/conditional-set-to/example-12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="a">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TrdCaptRpt">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="RptSide" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Pty" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute type="xs:string" name="R" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="TrdRegTS" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute type="xs:string" name="TS" use="optional"/>
                                                            <xs:attribute type="xs:string" name="Typ" use="optional"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="ClOrdID"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/conditional-set-to/example-12/example-12-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-12.xsd example-12.xsd">
    <a>
        <TrdCaptRpt>
            <RptSide ClOrdID="43401154-1">
                <Pty R="24"/>
                <TrdRegTS Typ="1" TS="2018-10-31T14:13:19.9Z"/>
            </RptSide>
            <RptSide ClOrdID="43401154-2">
                <Pty R="24"/>
                <TrdRegTS Typ="2" TS="2018-10-31T00:00:00.00Z"/>
            </RptSide>
        </TrdCaptRpt>
    </a>
</dataDocument>
