=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/conditional-set/example-9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="engineDetail" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="combustible">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="combustibleType" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="engineCategory" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/conditional-set/example-9/example-9-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-9.xsd example-9.xsd">
    <engineType>
        <engineDetail>
            <combustible>
                <combustibleType>Gasoline</combustibleType>
            </combustible>
        </engineDetail>
        <engineDetail>
            <combustible>
                <combustibleType>Diesel</combustibleType>
            </combustible>
        </engineDetail>
        <engineDetail>
            <combustible>
                <combustibleType>Propane</combustibleType>
            </combustible>
        </engineDetail>
        <engineCategory>Combustion</engineCategory>
    </engineType>
</dataDocument>
