=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/conditional-set/example-25.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="a">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="b" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="bId" />
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="optional" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="c" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bref">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="href" use="optional" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="pid" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rosetta-models/translate-demo/rosetta-source/src/main/resources/cdm-sample-files/conditional-set/example-25/example-25-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-25.xsd example-25.xsd">
    <a>
        <b id="source">
            <bId>source-bid</bId>
        </b>
        <b id="counter">
            <bId>counter-bid</bId>
        </b>
        <c>
            <bref href="counter"/>
            <pid>counter-pid</pid>
        </c>
        <c>
            <bref href="source"/>
            <pid>source-pid</pid>
        </c>
    </a>
</dataDocument>
