=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/multi-cardinality/example-26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="engineDetail" type="EngineDetail" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="fuelDetail" type="FuelDetail" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="capacityDetail" type="CapacityDetail" minOccurs="0"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="EngineDetail">
        <xs:all>
            <xs:element name="combustible" type="xs:string" minOccurs="0"/>
            <xs:element name="capacityUnit" minOccurs="0" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="FuelDetail">
        <xs:all>
            <xs:element name="combustible" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="CapacityDetail">
        <xs:all>
            <xs:element name="capacityUnit" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== rosetta-models/translate-demo/tests/src/test/resources/example-generation/inputs/multi-cardinality/example-26/example-26-3.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-26.xsd example-26.xsd">
    <engineType>
        <engineDetail>
            <combustible>Petrol</combustible>
        </engineDetail>
        <fuelDetail>
            <combustible>Diesel</combustible>
        </fuelDetail>
        <capacityDetail>
            <capacityUnit>Gallon</capacityUnit>
        </capacityDetail>
    </engineType>
</dataDocument>
