=== rosetta-models/translate-demo/rosetta-source/src/main/resources/schemas/multi-cardinality/example-27.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dataDocument">
        <xs:complexType>
            <xs:all>
                <xs:element name="engineType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="submitter" type="Identifier" maxOccurs="unbounded"/>
                            <xs:element name="walker" type="Identifier" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Identifier">
        <xs:sequence>
            <xs:element name="id" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== rosetta-models/translate-demo/rosetta-source/src/main/resources/cdm-sample-files/multi-cardinality/example-27/example-27-1.xml
<?xml version="1.0"?>
<dataDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="example-27.xsd example-27.xsd">
    <a>
        <submitter>
            <id>FISH</id>
            <id>CHIPS</id>
        </submitter>
        <walker>
            <id>SAUSAGE</id>
            <id>MASH</id>
        </walker>
    </a>
</dataDocument>
